#- name: install php repo
#  shell: rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
- name: install php 
  yum: name={{packages}}  state=present
  vars:
    packages:
       - php71w
       - php71w-cli
       - php71w-common
       - php71w-devel
       - php71w-embedded
       - php71w-embedded
       - php71w-gd
       - php71w-mcrypt
       - php71w-mbstring
       - php71w-pdo
       - php71w-xml
       - php71w-fpm
       - php71w-mysqlnd
       - php-opcache
       - php71w-pecl-memcached
       - php71w-pecl-redis
       - php71w-pecl-mongodb

#- name: config php
#  template: src=www.conf.j2  dest=/etc/php-fpm.d/www.conf
#  notify: restart php
 
#- name config php.ini
#  template: src=php.ini dest=/etc/php.ini
#  notify: restart php

- name: start php-fpm
  service: name=php-fpm state=started enabled=yes
