- name: install keepalived
  yum: name=keepalived state=present


- name: config keepalived
  template: src=keepalived.conf.j2  dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived


- name: start keepalived
  service: name=keepalived state=started enabled=yes
